#!/bin/bash
# Setup GitHub Secrets for Autonomous Loop

echo "Setting up GitHub Secrets for v0 Autonomous Loop..."
echo ""
echo "These secrets need to be added to: https://github.com/bbspaceme1/KBAI/settings/secrets/actions"
echo ""
echo "Copy and paste each one:"
echo ""
echo "1. VERCEL_PERSONAL_ACCESS_TOKEN"
echo "   (Get from https://vercel.com/account/tokens)"
echo ""
echo "2. VERCEL_ORG_ID"
echo "   Run: npx vercel whoami"
echo ""
echo "3. VERCEL_PROJECT_ID"
echo "   Run: npx vercel project list"
echo ""
echo "4. SUPABASE_URL"
echo "   (Get from https://supabase.com/dashboard → Settings → API)"
echo ""
echo "5. SUPABASE_ANON_KEY"
echo "   (Get from https://supabase.com/dashboard → Settings → API)"
echo ""
echo "6. SUPABASE_SERVICE_ROLE_KEY"
echo "   (Get from https://supabase.com/dashboard → Settings → API)"
echo ""
echo "7. JWT (if needed)"
echo "   (Your JWT token if applicable)"
echo ""
echo "8. JWT_2 (if needed)"
echo "   (Your JWT token if applicable)"
echo ""
echo "Once secrets are added, the autonomous loop will start automatically!"
