#!/bin/bash
# Setup GitHub Secrets for KBAI workflows

echo "Setting up GitHub Secrets for KBAI automated remediation..."
echo ""
echo "These secrets need to be added to: https://github.com/bbspaceme1/KBAI/settings/secrets/actions"
echo ""
echo "Copy and paste each one:"
echo ""
echo "1. VERCEL_TOKEN"
echo "   (Get from https://vercel.com/account/tokens)"
echo ""
echo "2. VERCEL_ORG_ID"
echo "   Run: npx vercel whoami"
echo ""
echo "3. VERCEL_PROJECT_ID"
echo "   Run: npx vercel project list"
echo ""
echo "4. SUPABASE_URL"
echo "   (Get from https://supabase.com/dashboard → Settings → API)"
echo ""
echo "5. SUPABASE_ANON_KEY"
echo "   (Get from https://supabase.com/dashboard → Settings → API)"
echo ""
echo "6. SUPABASE_SERVICE_ROLE_KEY"
echo "   (Get from https://supabase.com/dashboard → Settings → API)"
echo ""
echo "7. SUPABASE_ACCESS_TOKEN"
echo "   (Get from Supabase Account Settings > Access Tokens)"
echo ""
echo "See docs/GITHUB_SECRETS_REQUIRED.md for the complete secret checklist."
