ALTER TABLE public.idx_etl_logs ADD COLUMN IF NOT EXISTS expected_count integer;
ALTER TABLE public.idx_etl_logs ADD COLUMN IF NOT EXISTS missing_count integer;
ALTER TABLE public.idx_etl_logs ADD COLUMN IF NOT EXISTS duplicate_count integer;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'idx_etl_logs_status_check') THEN
    ALTER TABLE public.idx_etl_logs ADD CONSTRAINT idx_etl_logs_status_check CHECK (status IN ('success','partial','failed','rejected'));
  END IF;
END $$;
CREATE TABLE IF NOT EXISTS public.idx_missing_symbols (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  etl_log_id bigint NOT NULL REFERENCES public.idx_etl_logs(id) ON DELETE CASCADE,
  ticker varchar(10) NOT NULL,
  expected_reason text NOT NULL DEFAULT 'active_listing',
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(etl_log_id, ticker)
);
ALTER TABLE public.idx_missing_symbols ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS idx_missing_symbols_admin_select ON public.idx_missing_symbols;
CREATE POLICY idx_missing_symbols_admin_select ON public.idx_missing_symbols FOR SELECT TO authenticated USING (public.has_role((select auth.uid()), 'admin'::public.app_role));
CREATE INDEX IF NOT EXISTS idx_missing_symbols_log_idx ON public.idx_missing_symbols(etl_log_id);
